[project]
name = "pytorch-nlp-like-gpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "matplotlib>=3.10.0",
    "numpy>=2.2.2",
    "tiktoken>=0.8.0",
    "torch>=2.5.1",
]
